### ISSUE TITLE
No such file error with dftb-uv_2d

### ISSUE THREAD

**Issue by jychoi-hpc** [ORNL/Analysis-of-Large-Scale-Molecular-Datasets-with-Python#10]
While trying to run dftb-uv_2d.py, I got the following error messages and the program didn't stop at the end. It looks like some processes stopped and hangs:
```
[12:14:56] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:14:56] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:14:56] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:14:56] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:15:18] Explicit valence for atom # 2 C, 5, is greater than permitted
Traceback (most recent call last):
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 462, in <module>
    smooth_spectra(path, min_energy, max_energy, min_wavelength, max_wavelength)
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 404, in smooth_spectra
    smooth_spectrum(path + '/' + dir, min_energy, max_energy, min_wavelength, max_wavelength)
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 288, in smooth_spectrum
    mol2d_im = image.imread(f"{filename}/mol_2d_drawing.png")
  File "/global/cfs/cdirs/m4133/perlmutter/sw/anaconda3/2022.10/lib/python3.9/site-packages/matplotlib/image.py", line 1501, in imread
    with img_open(fname) as image:
  File "/global/cfs/cdirs/m4133/perlmutter/sw/anaconda3/2022.10/lib/python3.9/site-packages/PIL/ImageFile.py", line 104, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './dftb_gdb9_electronic_excitation_spectrum/mol_051405/mol_2d_drawing.png'
[12:15:25] Explicit valence for atom # 6 C, 5, is greater than permitted
Traceback (most recent call last):
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 462, in <module>
    smooth_spectra(path, min_energy, max_energy, min_wavelength, max_wavelength)
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 404, in smooth_spectra
    smooth_spectrum(path + '/' + dir, min_energy, max_energy, min_wavelength, max_wavelength)
  File "/pscratch/sd/j/jyc/HydraGNN-dataset/dftb-uv_2d.py", line 288, in smooth_spectrum
    mol2d_im = image.imread(f"{filename}/mol_2d_drawing.png")
  File "/global/cfs/cdirs/m4133/perlmutter/sw/anaconda3/2022.10/lib/python3.9/site-packages/matplotlib/image.py", line 1501, in imread
    with img_open(fname) as image:
  File "/global/cfs/cdirs/m4133/perlmutter/sw/anaconda3/2022.10/lib/python3.9/site-packages/PIL/ImageFile.py", line 104, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './dftb_gdb9_electronic_excitation_spectrum/mol_015481/mol_2d_drawing.png'
```

Any advice on how to fix?

**Comment by allaffa** [comment]
@jychoi-hpc 
For now, simply comment the following lines:
```
        mol2d_im = image.imread(f"{filename}/mol_2d_drawing.png")
        imagebox = OffsetImage(mol2d_im,zoom=0.5)
        ab = AnnotationBbox(imagebox, (max(plt_range_x)*0.8,max(plt_range_gauss_sum_y)*0.6), frameon = True)
        ax.add_artist(ab)
```
These lines are used only to plot the 2D structure of the molecule in the top right corner of the plot for the UV/vis spectrum. We don't need it to generate the file EXC-smooth.DAT.
